### ISSUE TITLE
Releasing requirements.txt file

### ISSUE THREAD

**Issue by shashankg7** [ArmanZarei/Mitigating-T2I-Compositionality-Issues#1]
Hi, 

Thank you for open-sourcing your work. Could you please release your requirements.txt file or the conda env file? 

Thanks.

**Comment by ArmanZarei** [comment]
Hi,

Thank you for your interest in the project! I've just uploaded the requirements.txt file to the repository. You can now find it [here](https://github.com/ArmanZarei/Mitigating-T2I-Comp-Issues/blob/main/requirements.txt). Please feel free to reach out if you have any further questions or need additional assistance.

Best,
Arman
